version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ctfd
      MYSQL_USER: ctfd
      MYSQL_PASSWORD: ctfd
    volumes:
      - db_data:/var/lib/mysql

  ctfd:
    image: ctfd/ctfd:latest
    restart: always
    environment:
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
    depends_on:
      - db
    ports:
      - "8000:8000"

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - ctfd

volumes:
  db_data:
